dist: bionic
language: c++

addons:
  apt:
    packages:
      - libboost-all-dev
      - python3-pip
      - python3-setuptools
      - python3-pandas
      - python3-numpy

compiler:
  - gcc

install:
  # the install step will take care of deploying a newer cmake version
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.17.0-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.17.0-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}
  # install required python packages
  - python3 -m pip install sklearn xgboost

script: 
  - cd ${TRAVIS_BUILD_DIR}
  - ln -s $PWD/benchmark/xgboost2tmva.py $PWD/test/xgboost2tmva.py
  - cd test && python3 create_test_data.py && cd ..
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - env CTEST_OUTPUT_ON_FAILURE=1 make test
